services:
  - docker

script:
  - sudo curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose run webserver npm install
  - docker-compose run webserver npm run lint
  - docker-compose run webserver npm run test