version: '3.7'

x-node:
  &node
  build: .
  image: dagflow_node
  volumes:
    - .:/code
    - ../keys:/keys
  environment:
    - REDIS_URL=redis://redis:6379
    - MONGO_URL=mongodb://mongo:27017/test
    - DEBUG=app:*
    - GOOGLE_APPLICATION_CREDENTIALS=/keys/dagflow2.json
    - CLOUDSDK_CORE_PROJECT=raporty-kamil
  working_dir: /code
  depends_on:
    - redis
    - mongo

services:
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db

  redis:
    image: "redis:alpine"
    volumes:
      - ./compose/redis/:/compose/redis
    healthcheck:
      test: ["CMD", "/compose/redis/docker-healthcheck"]

  orchester:
    <<: *node
    command: ./init.sh npx nodemon ./bin/dagflow orchester
    ports:
      - "8001:8000"

  webserver:
    <<: *node
    command: ./init.sh npx nodemon ./bin/dagflow webserver

    ports:
      - "8002:8000"

  worker:
    <<: *node
    command: ./init.sh npx nodemon ./bin/dagflow worker
    ports:
      - "8003:8000"

  kue:
    <<: *node
    command: ./init.sh npx nodemon ./bin/dagflow kue
    ports:
      - "8004:8000"

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8005:8081"
    depends_on:
      - mongo

volumes:
  mongo_data: